#**********************************************************
#* Notify
#**********************************************************
- alias: forward_persistent_notifications
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: persistent_notification
        service: create
  condition:
    - condition: state
      entity_id: input_boolean.debugmode
      state: 'off'
  action:
  - service: notify.telegram_notificaties
    data_template:
      message: >-
        {% set message = trigger.event.data.service_data.message %}
        {% if 'invalid authentication' in message or 'login attempts' in message %}
          {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
        {% else %}
          {{ message }}
        {% endif %}
