#**********************************************************
#* State
#**********************************************************
- alias: Motion_UpdateLast
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_buiten, binary_sensor.motion_slaapkamer_kdv, binary_sensor.motion_bijkeuken, binary_sensor.motion_leefruimte, binary_sensor.motion_hal, binary_sensor.motion_overloop, binary_sensor.motion_badkamer
      to: 'on'
  action:
    - service: variable.set_variable
      data:
        variable: last_motion
        attributes_template: >
           {
              "history_1": "{{ variable.state }}",
              "history_2": "{{ variable.attributes.history_1 }}",
              "history_3": "{{ variable.attributes.history_2 }}"
            }
      data_template:
        value: "{{ trigger.to_state.attributes.friendly_name }}"
