#**********************************************************
#* Contact
#**********************************************************
- alias: contact_brievenbus_on
  trigger:
    platform: state
    entity_id: binary_sensor.contact_brievenbus
    from: 'off'
    to: 'on'
  action:
  - service: notify.telegram_notificaties
    data_template:
      message: >-
        De brievenbus is geopend
#**********************************************************
#* Motion
#**********************************************************

#**********************************************************
#* State
#**********************************************************

#**********************************************************
#* Switch
#**********************************************************

#**********************************************************
#* Timers
#**********************************************************
