#*****************************************************************
#* AUTHOR  Lubbert Kramer terug
#* Github  https://github.com/lubbertkramer/home_assistant_config
#*****************************************************************

###
#Contact

#
# Contact and timer idle -> turn lights on
- alias: contact_bijkeuken_timer_idle
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.achterdeurcontact
        - binary_sensor.bijkeukencontact
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.bijkeukenlicht
        state: 'idle'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
      - condition: or  # 'when dark' condition: either after sunset or before sunrise
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-02:00:00'
          - condition: sun
            before: sunrise
            before_offset: '+02:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bijkeuken

#
# Contact and timer running -> reset timer
- alias: contact_bijkeuken_timer_on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.achterdeurcontact
        - binary_sensor.bijkeukencontact
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.bijkeukenlicht
        state: 'active'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.bijkeukenlicht
  - delay: '00:00:03'
  - service: timer.start
    entity_id: timer.bijkeukenlicht

###
#Motion

#
# Motion and timer idle -> turn lights on
- alias: motion_bijkeuken_timer_idle
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bijkeukenmotion01
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.bijkeukenlicht
        state: 'idle'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
      - condition: or  # 'when dark' condition: either after sunset or before sunrise
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-02:00:00'
          - condition: sun
            before: sunrise
            before_offset: '+02:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bijkeuken

#
# Motion and timer running -> reset timer
- alias: motion_bijkeuken_timer_on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.achterdeurmotion01
        - binary_sensor.bijkeukenmotion01
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.bijkeukenlicht
        state: 'active'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.bijkeukenlicht
  - delay: '00:00:03'
  - service: timer.start
    entity_id: timer.bijkeukenlicht

###
#Notify

###
#State

#
# State lights turned to on - start timer - when state emergency don't start timer
- alias: state_bijkeuken_light_on
  trigger:
    platform: state
    entity_id: light.bijkeuken
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.state_emergency
      state: 'off'
  action:
    - service: timer.start
      entity_id: timer.bijkeukenlicht

#
# State lights turned to off -> cancel timers
- alias: state_bijkeuken_light_off
  trigger:
    platform: state
    entity_id: light.bijkeuken
    from: 'on'
    to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.bijkeukenlicht

###
#Switch

#
# Switch
- alias: switch_bijkeuken
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bijkeukenschakelaar
      event: 1002
  action:
    - service: light.toggle
      entity_id: light.bijkeuken

###
#Time

###
#Timers

#
# Timer runs to zero
- alias: timer_bijkeuken_lights_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bijkeukenlicht
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.state_ignoretimers
        state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bijkeuken
