#*****************************************************************
#* AUTHOR  Lubbert Kramer terug
#* Github  https://github.com/lubbertkramer/home_assistant_config
#*****************************************************************

###
#Contact

#
# Contact and timer idle -> turn lights on
- alias: contact_overloopbadkamer_timer_idle
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.slpkdvcontact
        - binary_sensor.slpmendycontact
        - binary_sensor.slprobincontact
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.badkamerlicht
        state: 'idle'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
      - condition: or  # 'when dark' condition: either after sunset or before sunrise
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-02:00:00'
          - condition: sun
            before: sunrise
            before_offset: '+02:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.badkamer

#
# Contact and timer running -> reset timer
- alias: contact_overloopbadkamer_timer_on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.slpkdvcontact
        - binary_sensor.slpmendycontact
        - binary_sensor.slprobincontact
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.badkamerlicht
        state: 'active'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.badkamerlicht
  - delay: '00:00:03'
  - service: timer.start
    entity_id: timer.badkamerlicht


###
#Motion

#
# Motion and timer idle -> turn lights on
- alias: motion_overloopbadkamer_timer_idle
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.overloopkdvmotion
        - binary_sensor.overloopmendymotion
        - binary_sensor.overlooptrapmotion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.badkamerlicht
        state: 'idle'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
      - condition: or  # 'when dark' condition: either after sunset or before sunrise
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-02:00:00'
          - condition: sun
            before: sunrise
            before_offset: '+02:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.badkamer

#
# Motion and timer running -> reset timer
- alias: motion_overloopbadkamer_timer_on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.overloopkdvmotion
        - binary_sensor.overloopmendymotion
        - binary_sensor.overlooptrapmotion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.badkamerlicht
        state: 'active'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.badkamerlicht
  - delay: '00:00:03'
  - service: timer.start
    entity_id: timer.badkamerlicht


###
#Notify

###
#State

#
# State lights turned to on - start timer - when state emergency don't start timer
- alias: state_overloopbadkamer_light_on
  trigger:
    platform: state
    entity_id: light.badkamer
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.state_emergency
      state: 'off'
  action:
    - service: timer.start
      entity_id: timer.badkamerlicht

#
# State lights turned to off -> cancel timers
- alias: state_overloopbadkamer_light_off
  trigger:
    platform: state
    entity_id: light.badkamer
    from: 'on'
    to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.badkamerlicht


###
#Switch

#
###
#Time

###
#Timers


#
# Timer runs to zero
- alias: timer_overloopbadkamer_lights_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.badkamerlicht
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_timers
        state: 'off'
  action:
    service: light.turn_off
    entity_id: light.badkamer
