#*****************************************************************
#* AUTHOR  Lubbert Kramer terug
#* Github  https://github.com/lubbertkramer/home_assistant_config
#*****************************************************************

###
#Contact

#
# Contact and timer idle -> turn lights on
- alias: contact_toilet_timer_idle
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toiletcontact
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.toiletlicht
        state: 'idle'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.toilet

#
# Contact and timer running -> reset timer
- alias: contact_toilet_timer_on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toiletcontact
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.toiletlicht
        state: 'active'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.toilet

###
#Motion

#
# Motion and timer idle -> turn lights on
- alias: motion_toilet_timer_idle
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toiletmotion01
        - binary_sensor.toiletmotion02
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.toiletlicht
        state: 'idle'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.toilet

#
# Motion and timer running -> reset timer
- alias: motion_toilet_timer_on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toiletmotion01
        - binary_sensor.toiletmotion02
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.toiletlicht
        state: 'active'
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_lights
        state: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.toiletlicht
  - delay: '00:00:03'
  - service: timer.start
    entity_id: timer.toiletlicht

###
#Notify

###
#State

#
# State lights turned to on - start timer - when state emergency don't start timer
- alias: state_toilet_light_on
  trigger:
    platform: state
    entity_id: light.toilet
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.state_emergency
      state: 'off'
  action:
    - service: timer.start
      entity_id: timer.toiletlicht

#
# State lights turned to off -> cancel timers
- alias: state_toilet_light_off
  trigger:
    platform: state
    entity_id: light.toilet
    from: 'on'
    to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.toiletlicht

###
#Switch

#
# Switch
- alias: switch_toilet
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toiletschakelaar
      event: 1002
  action:
    - service: light.toggle
      entity_id: light.toilet

#
###
#Time

###
#Timers

#
# Timer runs to zero
- alias: timer_toilet_lights_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.toiletlicht
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.automation_all
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_timers
        state: 'off'
  action:
    service: light.turn_off
    entity_id: light.toilet
