#**********************************************************
#* Contact
#**********************************************************
- alias: contact_bijkeuken_on
  trigger:
    platform: state
    entity_id: binary_sensor.contact_bijkeuken, binary_sensor.contact_achterdeur
    to: 'on'
  condition:
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: "-01:00:00"
          - condition: sun
            before: sunrise
            before_offset: "+01:00:00"
  action:
    - service: timer.start
      entity_id: timer.bijkeuken_lampen
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if now().hour >= 0 and now().hour < 6 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_nacht
          {% elif now().hour >= 6 and now().hour < 18 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_dag
          {% elif now().hour >= 18 and now().hour < 24 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_avond
          {% elif is_state("light.bijkeuken", "on") %}
             script.nothing
          {% endif %}
#**********************************************************
#* Motion
#**********************************************************
- alias: motion_bijkeuken_timer_on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_bijkeuken, binary_sensor.motion_achterdeur
    to: 'on'
  condition:
    - condition: state
      entity_id: timer.bijkeuken_lampen
      state: 'active'
  action:
  - service: timer.cancel
    entity_id: timer.bijkeuken_lampen
  - service: timer.start
    entity_id: timer.bijkeuken_lampen

- alias: motion_bijkeuken
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.motion_bijkeuken
        - binary_sensor.motion_achterdeur
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
        - condition: sun
          before: sunrise
          before_offset: "+01:00:00"
  action:
    - service: timer.start
      entity_id: timer.bijkeuken_lampen
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if now().hour >= 0 and now().hour < 6 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_nacht
          {% elif now().hour >= 6 and now().hour < 18 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_dag
          {% elif now().hour >= 18 and now().hour < 24 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_avond
          {% elif is_state("light.bijkeuken", "on") %}
             script.nothing
          {% endif %}
#**********************************************************
#* State
#**********************************************************
- alias: state_bijkeuken_lamp
  trigger:
    platform: state
    entity_id: light.bijkeuken
    from: 'on'
    to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.bijkeuken_lampen
#**********************************************************
#* Switch
#**********************************************************
- alias: switch_bijkeuken
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_bijkeuken
      event: 1002
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if now().hour >= 0 and now().hour < 6 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_nacht
          {% elif now().hour >= 6 and now().hour < 18 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_dag
          {% elif now().hour >= 18 and now().hour < 24 and is_state("light.bijkeuken", "off") %}
             scene.bijkeuken_avond
          {% elif is_state("light.bijkeuken", "on") %}
             scene.bijkeuken_uit
          {% endif %}
#**********************************************************
#* Timers
#**********************************************************
- alias: timer_bijkeuken_lampen_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bijkeuken_lampen
  action:
    service: light.turn_off
    entity_id: light.bijkeuken
