#**********************************************************
#* Contact
#**********************************************************
- alias: contact_trapkast_on
  trigger:
    platform: state
    entity_id: binary_sensor.contact_trapkast
    from: 'off'
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.trapkast

- alias: contact_trapkast_off
  trigger:
    platform: state
    entity_id: binary_sensor.contact_trapkast
    from: 'on'
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.trapkast
#**********************************************************
#* Motion
#**********************************************************

#**********************************************************
#* State
#**********************************************************

#**********************************************************
#* Switch
#**********************************************************

#**********************************************************
#* Timers
#**********************************************************
